### ISSUE TITLE
ncdns's x509 fork doesn't build on Go 1.9+

### ISSUE THREAD

**Issue by vladsf** [namecoin/ncdns#44]
my host  MINGW64 ~/go
$ go get -t github.com/namecoin/ncdns/...
 # github.com/namecoin/ncdns/x509
 src\github.com\namecoin\ncdns\x509\x509_splice.go:67:36: not enough arguments in call to  buildExtensions
        have (*Certificate)
        want (*Certificate, []byte)

**Comment by JeremyRand** [comment]
90% sure this is the same issue that @jonasbits mentioned on Matrix recently.  It looks at first glance that the Go standard library changed the x509 internal API, and I'm going to have to merge their upstream changes for that.  I did a pretty good job of minimizing the amount of code that needs to periodically merge upstream changes, but even this code needs occasional merges.  As a short-term workaround, try using an older version of Go (whatever version the ncdns-nsis build scripts pull in should work).

**Comment by 9072997** [comment]
I changed /x509/x509_splice.go based on what the function call looked like in  /x509/x509.go, which solved this issue for me.

I replaced
```
extensions, err := buildExtensions(template, authorityKeyId)
```
with
```
extensions, err := buildExtensions(template, bytes.Equal(asn1Subject, emptyASN1Subject), authorityKeyId)
```

**Comment by JeremyRand** [comment]
Fixed by #65.
